ES-1166
mosip/esignet-signup pull request #225
Opened 2024-07-02 06:50 UTC by rathanak-0080

![image](https://github.com/mosip/esignet-signup/assets/148197234/a48a177a-4ed6-4018-81de-2b7734e7a411)

2024-07-02 06:52 UTC, bunsyy approved these changes

2024-07-02 06:56 UTC, bunsy-0900 approved these changes

2024-07-02 09:19 UTC, panharith-0118 approved these changes

2024-07-02 09:42 UTC, aranaravi requested changes

2024-07-02 09:42 UTC, aranaravi commented on signup-ui/src/pages/ResetPasswordPage/ResetPasswordStatus/ResetPasswordStatus.tsx
text-orange-500 to test-primary what is the reason for class change

2024-07-03 03:02 UTC, rathanak-0080 commented on signup-ui/src/pages/ResetPasswordPage/ResetPasswordStatus/ResetPasswordStatus.tsx
because `text-primary` value is change base on theme name.
https://github.com/mosip/esignet-signup/blob/ES-842/signup-ui/src/App.css#L291

2024-07-03 04:31 UTC, merged